# Generated by Django 3.2.9 on 2021-11-28 17:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razaosocial', models.CharField(max_length=100, verbose_name='Razão Social')),
                ('cnpj', models.CharField(max_length=20, verbose_name='CNPJ')),
                ('inscricao', models.CharField(max_length=15, verbose_name='Inscrição estadual')),
                ('nome', models.CharField(max_length=70, verbose_name='Nome fantasia')),
                ('produto', models.CharField(max_length=80, verbose_name='Produto')),
                ('endereco', models.CharField(max_length=50, verbose_name='Endereço')),
                ('bairro', models.CharField(max_length=50, verbose_name='Bairro')),
                ('cidade', models.CharField(max_length=50, verbose_name='Cidade')),
                ('uf', models.CharField(max_length=2, verbose_name='Estado')),
                ('cep', models.CharField(max_length=9, verbose_name='CEP')),
                ('telefone', models.CharField(max_length=10, verbose_name='Telefone')),
                ('email', models.CharField(max_length=50, verbose_name='E-mail')),
                ('insercoes', models.CharField(max_length=100, verbose_name='Inserções')),
                ('tipo_insercao', models.CharField(choices=[('Testemunhal', 'Testemunhal'), ('Texto Gravado', 'Texto Gravado'), ('Pedagio', 'Pedágio')], max_length=15, verbose_name='Tipo de inserção')),
                ('pagamento', models.CharField(choices=[('avista', 'Avista'), ('parcelado', 'Parcelado'), ('cartao', 'Cartão de Crédito')], max_length=15, verbose_name='Tipo de pagamento')),
                ('valor_total', models.CharField(max_length=12, verbose_name='Valor do contrato')),
                ('parcelas', models.CharField(max_length=2, verbose_name='Quantidade de parcelas')),
                ('valor_parcelas', models.CharField(max_length=12, verbose_name='Valor das parcelas')),
                ('vencimento', models.CharField(max_length=2, verbose_name='Dia do vencimento')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
